
var CITYS = [
    "APO Apartado (Apartado) Colombia",
    "ACR Araracuara (Solano) Colombia",
    "BSC José Celestino Mutis(Bahía Solano) Colombia",
    "BAQ Barranquilla (Ernesto Cortissoz) Colombia",
    "EOH Olaya Herrera(Medellin) Colombia",
    "BOG Bogota (Eldorado) Colombia",
    "BGA Bucaramanga (Palo Negro) Colombia",
    "BUN Buenaventura (Buenaventura) Colombia",
    "CLO Cali (Alfonso B. Aragon) Colombia",
    "CTG Cartagena (Rafael Nunez) Colombia",
    "CZU Corozal (Corozal) Colombia",
    "CUC Cucuta (Camilo Daza) Colombia",
    "EYP El Yopal (El Yopal) Colombia",
    "FLA Florencia (Capitolio) Colombia",
    "GPI Kalispell  (Aeropuerto Internacional Glacier) Colombia",
    "IPI Ipiales (San Luis) Colombia",
    "CLR La Chorrera Colombia",
    "LMC La Macarena Colombia",
    "LPD La Pedrera Colombia",
    "LET Leticia (Gen. A.V. Cobo) Colombia",
    "MDE Medellin (José María Cordova) Colombia",
    "MVP Mitu (Mitu) Colombia",
    "MMP Mompox",
    "MTB Montelibano",
    "NQU Nuqui",
    "PSO Pasto (Cano) Colombia",
    "PTX Pitalito (Pitalito) Colombia",
    "PVA Providencia (Providencia) Colombia",
    "PUU Puerto Asis (Puerto Asis) Colombia",
    "PCR Puerto Carreño",
    "PDA Puerto Inirida (Puerto Inirida) Colombia",
    "LQM Puerto Leguizamo (Puerto Leguizamo) Colombia",
    "UIB Quibdo",
    "ADZ San Andres Islas (Gustavo Rojas Pinilla) Colombia",
    "SJE San Jose del Guaviare",
    "SVI San Vicente del Caguan",
    "RVE Saravena (Saravena) Colombia",
    "TME Tame",
    "TCD Tarapaca",
    "TCO Tumaco (La Florida) Colombia",
    "VGZ Villagarzon",
    "VVC Villavicencio (La Vanguardia) Colombia"
];